### PR TITLE
feat: hts task

### PR DESCRIPTION
**Pull request by bguiz**
- implementation of the HTS task in go
- translated from the HTS task in js
    - see: https://github.com/hedera-dev/hello-future-world-js/blob/main/hts/script-hts-ft.js

### CODE REVIEW

**Review by theekrystallee — APPROVED** [review]
LGTM

**Comment by SimiHunjan** [comment]
Tested this and looks good!

```
🏁 Hello Future World - HCS Topic - start
Using account: 0.0.1455
Using operatorKey: 1a83c7c0fe90a1d24b8f5bcd3b074aecad834d7a9fbe130ea133eb4e01775300
🟣 Creating new HCS topic
The topic create transaction ID: 0.0.1455@1726537146.418055595
Topic ID: 0.0.4863322
🟣 Publish message to HCS topic
The topic message submit transaction ID: 0.0.1455@1726537146.005985570
Topic Message Sequence Number: 1
🟣 View the topic on HashScan
Topic Hashscan URL: https://hashscan.io/testnet/topic/0.0.4863322
🟣 Get topic data from the Hedera Mirror Node
The token Hedera Mirror Node API URL: https://testnet.mirrornode.hedera.com/api/v1/topics/0.0.4863322/messages?encoding=base64&limit=5&order=asc&sequencenumber=1
Messages retrieved from this topic:
#1: Hello HCS!
🎉 Hello Future World - HCS Topic - complete
```

**Comment by SimiHunjan** [comment]
Same comment as the other PR: Should we consider adding the breaks between the steps for now or are we planning to add the same flow as JS where the user hit enter to move to the next step?

**Comment by bguiz** [comment]
thanks for reviewing @simihunjan + @theekrystallee

**Pull request merged**
